@url = http://127.0.0.1:8080/autores
GET {{url}}

###
GET {{url}}/1

###
POST {{url}}
Content-Type: application/json

{
    "titulo" : "A Sociedade do Anel",
    "id_genero" : 2
}

###
PUT {{url}}/1
Content-Type: application/json

{
    "nome" : "romance"
    
}

###
DELETE {{url}}/4